processed 35 tasks

init:
A: object(100)

task 1 'publish'. lines 6-210:
created: object(104)
written: object(103)

task 2 'run'. lines 213-213:
written: object(105)

task 3 'run'. lines 215-215:
created: object(107)
written: object(106)

task 4 'run'. lines 217-217:
written: object(108)
deleted: object(107)

task 5 'run'. lines 219-219:
created: object(110)
written: object(109)

task 6 'run'. lines 221-221:
created: object(112)
written: object(110), object(111)

task 7 'run'. lines 223-226:
written: object(113)
deleted: object(110), object(112)

task 8 'run'. lines 229-229:
created: object(115)
written: object(114)

task 9 'run'. lines 231-231:
Error: Transaction Effects Status: Entry Argument Type Error. Error for argument at index 0: Type mismatch.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: EntryArgumentError(EntryArgumentError { argument_idx: 0, kind: TypeMismatch }), source: Some("Expected argument of type Test::M::Obj, but found type Test::M::AnotherObj") } }

task 10 'run'. lines 233-233:
created: object(118)
written: object(117)

task 11 'run'. lines 235-235:
created: object(120)
written: object(119)

task 12 'run'. lines 237-237:
Error: Transaction Effects Status: Entry Argument Type Error. Error for argument at index 0: Type mismatch.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: EntryArgumentError(EntryArgumentError { argument_idx: 0, kind: TypeMismatch }), source: Some("Expected argument of type Test::M::Obj, but found type Test::M::AnotherObj") } }

task 13 'run'. lines 239-239:
created: object(123)
written: object(122)

task 14 'run'. lines 241-241:
Error: Transaction Effects Status: Entry Argument Type Error. Error for argument at index 0: Immutable and shared objects cannot be passed by-value.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: EntryArgumentError(EntryArgumentError { argument_idx: 0, kind: InvalidObjectByValue }), source: Some("Immutable and shared objects cannot be passed by-value, violation found in argument 0") } }

task 15 'run'. lines 243-243:
created: object(126)
written: object(125)

task 16 'run'. lines 245-245:
Error: The transaction inputs contain duplicates ObjectRef's

task 17 'run'. lines 247-247:
created: object(129)
written: object(128)

task 18 'run'. lines 249-252:
Error: The transaction inputs contain duplicates ObjectRef's

task 19 'run'. lines 255-255:
created: object(132)
written: object(131)

task 20 'run'. lines 257-257:
written: object(133)
deleted: object(132)

task 21 'run'. lines 259-259:
created: object(135)
written: object(134)

task 22 'run'. lines 261-261:
created: object(137)
written: object(135), object(136)

task 23 'run'. lines 263-266:
written: object(138)
deleted: object(135), object(137)

task 24 'run'. lines 269-269:
created: object(140)
written: object(139)

task 25 'run'. lines 271-271:
Error: Transaction Effects Status: Entry Argument Type Error. Error for argument at index 0: Type mismatch.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: EntryArgumentError(EntryArgumentError { argument_idx: 0, kind: TypeMismatch }), source: Some("Expected argument of type Test::M::ObjAny<T0>, but found type Test::M::AnotherObjAny<Test::M::Any>") } }

task 26 'run'. lines 273-273:
created: object(143)
written: object(142)

task 27 'run'. lines 275-275:
created: object(145)
written: object(144)

task 28 'run'. lines 277-277:
Error: Transaction Effects Status: Entry Argument Type Error. Error for argument at index 0: Type mismatch.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: EntryArgumentError(EntryArgumentError { argument_idx: 0, kind: TypeMismatch }), source: Some("Expected argument of type Test::M::ObjAny<T0>, but found type Test::M::AnotherObjAny<Test::M::Any>") } }

task 29 'run'. lines 279-279:
created: object(148)
written: object(147)

task 30 'run'. lines 281-281:
Error: Transaction Effects Status: Entry Argument Type Error. Error for argument at index 0: Immutable and shared objects cannot be passed by-value.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: EntryArgumentError(EntryArgumentError { argument_idx: 0, kind: InvalidObjectByValue }), source: Some("Immutable and shared objects cannot be passed by-value, violation found in argument 0") } }

task 31 'run'. lines 283-283:
created: object(151)
written: object(150)

task 32 'run'. lines 285-285:
Error: The transaction inputs contain duplicates ObjectRef's

task 33 'run'. lines 287-287:
created: object(154)
written: object(153)

task 34 'run'. lines 289-289:
Error: The transaction inputs contain duplicates ObjectRef's
